### PR TITLE
Issue 69303

### LINKED ISSUE #105: oss-fuzz: Issue 69303: opennavsurf-bag:bag_read_fuzzer: Crash in H5HG__cache_heap_deserialize
oss-fuzz: https://bugs.chromium.org/p/oss-fuzz/issues/detail?id=69303
details: https://oss-fuzz.com/testcase-detail/5902687177605120

### PR DESCRIPTION
**Pull request by anthonypapetti**
Fixes #105 

This creates protector functions that wrap the functions H5DFOpen() and H5GFOpen in try/catch statements in order to prevent a segmentation fault, and returns -1 on a fault to properly catch it and continue the program gracefully.

### CODE REVIEW

**Comment by selimnairb** [comment]
@anthonypapetti Sorry it took me so long to get to this. In the future I will trigger builds faster. However, it looks like these changes resulted in a few test cases failing, see [here](https://github.com/OpenNavigationSurface/BAG/actions/runs/11407530902/job/32718834881?pr=125) for example. Can you resolve these issues? Thanks.

**Comment by anthonypapetti** [comment]
> @anthonypapetti Sorry it took me so long to get to this. In the future I will trigger builds faster. However, it looks like these changes resulted in a few test cases failing, see [here](https://github.com/OpenNavigationSurface/BAG/actions/runs/11407530902/job/32718834881?pr=125) for example. Can you resolve these issues? Thanks.

Sounds good, I'll take a look at it. Thanks.

File: api/bag_dataset.cpp [hunk 1]
```diff
@@ -1056,6 +1056,27 @@ std::tuple<double, double> Dataset::gridToGeo(
...
+    } catch (std::exception& e) {
+        id = -1;
+    }
+    return id;
+}
+
+hid_t GopenProtector2(hid_t loc_id, const char *name, hid_t dapl_id) {
+    hid_t id = -1;
+    try {
+        id = H5Dopen2(loc_id, name, dapl_id);
```
Comment (selimnairb) [inline api/bag_dataset.cpp:1073]: Looks like a copy-paste type here. Should this be calling `H5Gopen2` instead of `H5Dopen2`?

Comment (anthonypapetti) [reply api/bag_dataset.cpp]: Thanks, fixed that. Probably will not fix tests but it's good to have anyway
